### ISSUE TITLE
missing-error ENV flag does not appear to be respected

### ISSUE THREAD

**Issue by ZacSweers** [buildkite-plugins/test-collector-buildkite-plugin#50]
We have a step defined like below

```yml
      - label: Run Physical Device Tests
        commands:
          - "ci/common/physical_device_test.sh"
        key: "physical_device_test_skippy"
        # other args omitted for brevity
        soft_fail: true
        env:
          ENABLE_SKIPPY: "true"
        plugins:
          - test-collector#v1.8.0:
              files: "**/build/fladle/*/results/*/JUnitReport.xml"
              format: "junit"
              debug: true
              api-token-env-name: ...
        retry: *retry_errors
        timeout_in_minutes: 60
```

The `physical_device_test.sh` script invoked in the command may sometimes intelligently skip running tests, so we want dynamically set the test-collector to exit with `0` in this case when it doesn't find any files. In practice the script does this in that event

```bash
export BUILDKITE_PLUGIN_TEST_COLLECTOR_MISSING_ERROR='0'
```

But it seems that this env is not respected when the plugin runs. Is it possible that it's resolving this env too eagerly (i.e. beginning of the step) rather than at test-result-collection-time? Or are we misunderstanding how that env is supposed to be used (or is it not visible to the test-collector plugin since it's set in the `commands` block)?
